### ISSUE TITLE
browserify can't deal with sub modules with files that don't end with .js

### ISSUE THREAD

**Issue by kolodny** [browserify/browserify#1308]
For example:

``` bash
cd tmpDir
npm init
npm install browserify mocha
echo 'require("mocha")' > index.js
./node_modules/.bin/browserify index.js
```

I get an error like this:

```
Error: Cannot find module './runnable' from '/Users/Moshe/tmp/node_modules/mocha'
    at /Users/Moshe/tmp/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/Moshe/tmp/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/Moshe/tmp/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/Moshe/tmp/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:78:15)
```

If I change `'../runnable'` to `'../runnable.js'` then the next time I run it I get an error about the next file that doesn't have a `.js` in it

using iojs 1.8.1

**Comment by zertosh** [comment]
I took a quick look, and they're creating a browser build as `mocha.js` but that file needs to be run through [derequire](https://github.com/calvinmetcalf/derequire) before they distribute it. Browserify is seeing a "require()" call and trying to locate that file, but that file is already a built bundle.

As a workaround, you can skip parsing of the entire module since it seems that their bundled version has everything you need:

```
./node_modules/.bin/browserify --noparse=$PWD/node_modules/mocha/mocha.js index.js
```
