### ISSUE TITLE
JavaScript console: bundle.js:55961: SyntaxError: Cannot declare a parameter named 'error' as it shadows the name of a strict mode function.

### ISSUE THREAD

**Issue by loretoparisi** [browserify/browserify#1597]
I get this error on a `WebView` using https://github.com/MacGapProject/MacGap1

and

``` shell
$ browserify --version
13.0.1
```

**Comment by terinjokes** [comment]
JavaScriptCore, Safari's JavaScript interpreter, doesn't follow the spec in ES5 strict mode, and has caused horrible issues similar to this since at least 2012/2013. I believe it's fixed in the Safari Technical Preview (and thus future versions of JavaScriptCore) to be compatible with ES6.

I believe UglifyJS2 has logic to avoid this situation. If you minify the output from Browserify, it should work.

**Comment by goto-bus-stop** [comment]
this sort of thing is likely caused by a module in the bundle, not by browserify itself.
