### ISSUE TITLE
Function missing after browserify

### ISSUE THREAD

**Issue by 1vadios** [browserify/browserify#1662]
Hi, I’m trying to use the library [mysql](https://www.npmjs.com/package/mysql) on a client in combination with Cordova.
It works until the program reaches the point where it has to connect to the database. The problem is that the function for the connect isn’t defined in the bundle.js.

Error:
`Uncaught TypeError: Net.createConnection is not a function`

In the library is the 'net' required and so inserted (var Net = require('net');), so shouldn’t browserify insert that one as well in the bundle.js, that the function is available?

**Comment by MellowMelon** [comment]
Browserify inserts by default an implementation of that module suitable for browsers. Said implementation provides you basically nothing because browsers can't do any of the stuff that the net module does.

If you are not running the bundle in a browser, then you probably don't want the browser-suitable version of node's core. Try creating the bundle with `--no-builtins`; that will give you the usual net module.

If you are running the bundle in a browser, all browserify can do for you is insert your desired net module implementation in the correct places, but you will have to figure out what that implementation is yourself.

**Comment by 1vadios** [comment]
Thx will try it out.

**Comment by goto-bus-stop** [comment]
i'm assuming this was resolved—please comment or open a new issue if not. thanks!
