### ISSUE TITLE
How to bundle multi entry point by command

### ISSUE THREAD

**Issue by ChuanyuWang** [browserify/browserify#1777]
I tried different ways, while I got suck about below command
```
watchify -e src/main.js -e src/main2.js -o dist/build.js -o dist/build2.js"
```
I have several pages, each page has one entry file(module). I don't know how to build them.
I can't use several command to build files. Because I need to add plugin `browserify-hmr` to enable hot reload.
Anyone can help me out?

Many thanks~

**Comment by substack** [comment]
You should check out [factor-bundle](http://github.com/browserify/factor-bundle) which enables you to output to multiple bundle files. However, you will have 3 bundles, not 2 because the common dependencies will go into the third file.

Another option is [split-require](https://github.com/goto-bus-stop/split-require) which you can use to asynchronously load additional bundles from the same bundle.

**Comment by ChuanyuWang** [comment]
Thanks for the reply, I think I understand the design of browserify, and my question seems silly :)
