### ISSUE TITLE
"TypeError: exists is not a function"

### ISSUE THREAD

**Issue by EmperorSuper** [browserify/browserify#1795]
When ever I try to run a script I bundled with browserify it gives me the error:

```sh
Uncaught TypeError: exists is not a function
    at Function.getRoot (strobe_bundle.js:7582)
    at bindings (strobe_bundle.js:7484)
    at Object.122.../util (strobe_bundle.js:42457)
    at s (strobe_bundle.js:1)
    at strobe_bundle.js:1
    at Object.<anonymous> (strobe_bundle.js:42033)
    at Object.118../darwin (strobe_bundle.js:42036)
    at s (strobe_bundle.js:1)
    at strobe_bundle.js:1
    at Object.128../bindings/auto-detect (strobe_bundle.js:42897)
getRoot @ strobe_bundle.js:7582
bindings @ strobe_bundle.js:7484
122.../util @ strobe_bundle.js:42457
s @ strobe_bundle.js:1
(anonymous) @ strobe_bundle.js:1
(anonymous) @ strobe_bundle.js:42033
118../darwin @ strobe_bundle.js:42036
s @ strobe_bundle.js:1
(anonymous) @ strobe_bundle.js:1
128../bindings/auto-detect @ strobe_bundle.js:42897
s @ strobe_bundle.js:1
(anonymous) @ strobe_bundle.js:1
detect @ strobe_bundle.js:14766
Board @ strobe_bundle.js:15016
140.johnny-five @ strobe_bundle.js:44167
s @ strobe_bundle.js:1
e @ strobe_bundle.js:1
(anonymous) @ strobe_bundle.js:1
```
In console, can anyone help?

Here is my original unbundled code
`var five = require("johnny-five"),
    board = new five.Board();

board.on("ready", function() {
  // Create an Led on pin 13
  var led = new five.Led(13);

  // Strobe the pin on/off, defaults to 100ms phases
  led.strobe();
});`

I put it in a pastebin if that helps https://pastebin.com/bu1r8iFg
Thanks

**Comment by goto-bus-stop** [comment]
`johnny-five` depends on native C++ modules, which are not available in the browser. browsers can't talk directly to most devices, which the johnny-five library needs to do in order to control robots. you should run your johnny-five scripts directly in node without browserifying them.

(although a spec called WebUSB is in the works that may enable browsers talking to USB devices in the future!)

**Comment by EmperorSuper** [comment]
Ok, thanks for telling me, Do you know of a way to allow node to communicate with the browser in a way that would let johnny-five work?
As you can probably see I'm new to this and would appreciate any help I can get :D

**Comment by goto-bus-stop** [comment]
you could set up a small Node server that uses johnny-five, and run it separately. Then in the scripts that you pass to browserify, you would talk to that server instead of using johnny-five directly.

https://www.npmjs.com/package/dnode is a nice package that you can use to make the client/server communication easier.

**Comment by realisation** [comment]
I've gotten this problem when trying to bundle an application of mine with browserify. However, I don't use anything that refers to c++ bindings. If I recall correctly, leveldb is supposed to run in the browser. Must be missing something here.

**Comment by realisation** [comment]
https://github.com/browserify/browserify/issues/1805
