### ISSUE TITLE
Browserify and then eval the browsefied bundle file

### ISSUE THREAD

**Issue by sujayvenaik** [browserify/browserify#1814]
Had a local module. Browserified that using the standalone option.
When I require that particular file I can make use of my functions which I had exported.
But when I read that file using fs and try to eval that particular file it returns me as undefined.

If any specific option need to be passed or any other help. ?

**Comment by goto-bus-stop** [comment]
Standalone bundles use UMD, which tries to:

 - Set `module.exports` if it exists, or
 - Set a global variable

Bundles do not return anything.

You can use `var value = require('./path/to/bundle.js')`, and it will assign module.exports, so that works.

If you really need to `eval`, you can fake a module.exports object:

```js
var src = fs.readFileSync('./path/to/bundle.js', 'utf8')
var wrapped = 'var module = {exports: {}}; ' + src + '; return module.exports'

var value = eval(wrapped) // detects module.exports, sets it, then returns it
```

**Comment by goto-bus-stop** [comment]
Please comment or open a new issue if that did not do the trick. thanks!
