### ISSUE TITLE
Uncaught Error: Node's Buffer() not available

### ISSUE THREAD

**Issue by KingTsunamy** [browserify/browserify#1830]
I try to compile the img2gcode module with this app.js code 
var img2gcode = require("img2gcode");
img2gcode
  .start({  // It is mm
    toolDiameter: 1,
    scaleAxes: 700,
    deepStep: -1,
    feedrate: { work: 1200, idle: 3000 },
    whiteZ: 0,
    blackZ: -2,
    safeZ: 1,
    info: "emitter", // "none" or "console" or "emitter"
    dirImg: __dirname + '/1.jpg'
  })
  .on('log', (str) => {
    console.log(str);
  })
  .then((data) => {
    console.log(data.dirgcode);
  });
and I got Uncaught Error: Node's Buffer() not available

Does anyone has a solution for this? I tried with require buffer but it didn't worked

**Comment by goto-bus-stop** [comment]
I don't think that module will work in the browser. Judging by the `dirImg` option, it requires filesystem access, which is not possible with browser JS.

**Comment by KingTsunamy** [comment]
Can it be changed to take an url or the best thing would be to take data from a input file or a canvas

**Comment by goto-bus-stop** [comment]
So img2gcode itself doesn't support URLs or streams, but the error message you're running into is this one: https://github.com/oliver-moran/jimp/issues/280 I guess you can't do much about that unfortunately because you don't depend on jimp directly.

This doesn't appear to be a browserify issue so I'll close it, sorry I couldn't be more helpful—your best bet might be to ask for browser support in img2gcode.
