### ISSUE TITLE
Exists is not a function

### ISSUE THREAD

**Issue by FelipeValencio** [browserify/browserify#1926]
i know that this issue has been posted before, and yes i tried everything they said
i'm using the command `browserify test.js -o bundle.js`
my html is
`<html>
    <body>
        <script src="bundle.js"></script>
        <button onclick="connect()">Conectar</button>
    </body>
</html> `

i'm using webusb and escpos in my project

help please

**Comment by goto-bus-stop** [comment]
Most likely those modules simply do not work in the browser no matter what you do.

The WebUSB is impossible to polyfill in the browser and so can only work if the browser has builtin support for it. To use it in the browser you should use the builtin APIs instead of the `webusb` module.

For `escpos`, I don't know what it needs, but it probably doesn't work in the browser yet because the USB spec is so new.
