### ISSUE TITLE
process.env code is removed from output code

### ISSUE THREAD

**Issue by jcubic** [browserify/browserify#1967]
I want to convert library that use process.env that have code like this:

```javascript
const {env} = process;
// ...
if ('FORCE_COLOR' in env) {
	if (env.FORCE_COLOR === 'true') {
		forceColor = 1;
	} else if (env.FORCE_COLOR === 'false') {
		forceColor = 0;
	} else {
		forceColor = env.FORCE_COLOR.length === 0 ? 1 : Math.min(parseInt(env.FORCE_COLOR, 10), 3);
	}
}
```

and the code get removed completely, and If I have this:

```javascript
process.env.FORCE_COLOR = '3';
window.supportsColor = require('supports-color');
window.gradient = require('gradient-string');
```

the supports-color is used by chalk, because of this you're not able to use any library that use chalk to generate ANSI escape codes in browser. Becasue there is not tell that library that I actually support colors. the only way is command line option or environment variables.

**Comment by goto-bus-stop** [comment]
This is because supports-color uses a [`browser` field](https://github.com/defunctzombie/package-browser-field-spec):

https://github.com/chalk/supports-color/blob/651576a5fabfa489660b48f50a7f2e5ed7676997/package.json#L52

That line tells browserify to use this file instead of index.js:
https://github.com/chalk/supports-color/blob/master/browser.js

If you are not bundling code for the browser, you can use the --no-browser-field flag.
